# github.com/go-task/task

version: '3'

vars:
  BINARY_NAME: kubemq-targets
  VERSION: v1.7.1
tasks:
  default:
    cmds:
      - go build -buildmode=exe -o "{{.BINARY_NAME}}.exe"
      - ./kubemq-targets.exe
  check_update:
    cmds:
      - go-mod-upgrade
  lint:
    cmds:
      - golangci-lint run --disable gocritic --enable misspell
  goreleaser:
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist
  build_container:
    env:
      GOOS: '{{OS}}'
      GOARCH: '{{ARCH}}'
    cmds:
      - go build -tags container -o  "{{.BINARY_NAME}}.exe" -ldflags "-X main.version={{.VERSION}}"
  test:
    cmds:
      - go test -timeout 30m ./...
  build:
    env:
      GOOS: '{{OS}}'
      GOARCH: '{{ARCH}}'
    cmds:
      - go mod tidy
      - go mod vendor
      - go build -buildmode=exe -o "{{.BINARY_NAME}}.exe" -ldflags "-X main.version={{.VERSION}}"
  build-386:
    env:
      GOOS: linux
      GOARCH: 386
    cmds:
      - go mod tidy
      - go mod vendor
      - go build -o "{{.BINARY_NAME}}.exe" -ldflags "-X main.version={{.VERSION}}"
  docker-builder:
    cmds:
      - DOCKER_BUILDKIT=0  docker build . -f Docker_builder -t kubemq/gobuilder-ubuntu:latest
      - docker push kubemq/gobuilder-ubuntu:latest
  docker:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go mod tidy
      - go mod vendor
      - DOCKER_BUILDKIT=0 docker build --build-arg VERSION={{.VERSION}} . -t kubemq/{{.BINARY_NAME}}:{{.VERSION}}
      - docker tag kubemq/{{.BINARY_NAME}}:{{.VERSION}} kubemq/{{.BINARY_NAME}}:latest
  run_docker:
    cmds:
      - docker run -it --rm kubemq/{{.BINARY_NAME}}:latest
  push:
    cmds:
      - docker push kubemq/{{.BINARY_NAME}}:{{.VERSION}}
      - docker push kubemq/{{.BINARY_NAME}}:latest
  update-manifest:
    cmds:
      - go build -buildmode=exe -o "{{.BINARY_NAME}}.exe"
      - ./{{.BINARY_NAME}}.exe --manifest
  commit-modifed:
    cmds:
      - git add -A
      - git commit -a -m "release {{.VERSION}}"
      - git push origin master
  tag:
    cmds:
      - git tag -a {{.VERSION}} -m {{.VERSION}}
      - git push origin master --tags
  release:
    cmds:
      - go mod vendor
      - task: update-manifest
      - task: commit-modifed
      - task: docker
      - task: push
      - task: tag
  trivy:
    cmds:
      - trivy image --exit-code 1 --severity HIGH,CRITICAL kubemq/{{.BINARY_NAME}}:{{.VERSION}}
