# github.com/go-task/task

version: '2'

vars:
  BINARY_NAME: kubemq-targets
  VERSION: v0.1.4

tasks:
  check_update:
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct
  lint:
    cmds:
      - golangci-lint run --disable gocritic --enable misspell --enable gosec
  test:
    cmds:
      - go test -timeout 30m ./...
  docker:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go mod tidy
      - go mod vendor
      - docker build --build-arg VERSION={{.VERSION}} . -t kubemq/{{.BINARY_NAME}}:{{.VERSION}}
      - docker tag kubemq/{{.BINARY_NAME}}:{{.VERSION}} kubemq/{{.BINARY_NAME}}:latest
  release:
    cmds:
      - task: docker
      - docker push kubemq/{{.BINARY_NAME}}:{{.VERSION}}
      - docker push kubemq/{{.BINARY_NAME}}:latest
